### ISSUE TITLE
Visual glitch on Lancer - Kiyohime's Q Spell - Passionate Summer

### ISSUE THREAD

**Issue by SinisterLuffy5** [MeiMeiSama/ACR#14]
Sometimes, enemy units take damage before the effect appears if the target point is far from Lancer.
![LancerQ](https://github.com/user-attachments/assets/96d0ff3d-a9f1-49e8-a6ad-2380f1a69dff)

**Comment by null15** [comment]
Known bug on her, we've done some attempts to fix it but behaves very weirdly, might rework the Q.
